#!/bin/sh
echo "Initializing deployment of your site from repo...."
git checkout -f
echo "Initialization has completed  beensuccessfully"


echo "-------> Deployment has started..."

# Checkout the real 'master' so we can view the repo files
SERVICE='foreman'
LOG_FILE="app.log"
WORKING_DIR=`exec git config --get core.worktree`
REPO_PRE_DEPLOY_SCRIPT="$WORKING_DIR"/mungo_pre_deploy
REPO_POST_DEPLOY_SCRIPT="$WORKING_DIR"/mungo_post_deploy
REPO_PROCFILE="$WORKING_DIR"/Procfile
chmod -Rf 0755 $REPO_PROCFILE
chmod -Rf 0755 $REPO_POST_DEPLOY_SCRIPT
chmod -Rf 0755 $REPO_PRE_DEPLOY_SCRIPT

chmod -Rf 0777 $WORKING_DIR

cd $WORKING_DIR

function start_app() {
  
  # If the repository has a file called 'Procfile' then run it by foreman
  if [ -x "$REPO_PROCFILE" ]; then

    if ps ax | grep -v grep | grep $SERVICE > /dev/null
    then
        FOREMAN_ID=`ps aux | grep foreman | grep -v grep | awk '{print $2}'`
        echo "$SERVICE service already running, with process id $FOREMAN_ID..Trying to kill it.."
        kill $FOREMAN_ID
        nohup foreman start > mungo_app.log  &

        if ps ax | grep -v grep | grep $SERVICE > /dev/null 
        then
              echo "$SERVICE service restarted with process id $FOREMAN_ID, everything is fine"  & exit
        else
              echo "Unable to start $SERVICE"
              tail -f mungo_app.log & exit
        fi   

        
        

    else
        echo "$SERVICE is not running"
        echo "$SERVICE trying to start foreman"
        nohup foreman start > mungo_app.log  &
        FOREMAN_ID=`ps aux | grep foreman | grep -v grep | awk '{print $2}'`

       if ps ax | grep -v grep | grep $SERVICE > /dev/null 
       then
              echo "$SERVICE service running with process id $FOREMAN_ID, everything is fine"
       else
              echo "Unable to start $SERVICE"
              tail -f mungo_app.log    
       fi

    fi





         # If the repository has a file called 'mungo_deploy' then run it
         if [ -x "$REPO_POST_DEPLOY_SCRIPT" ]; then
                exec "$REPO_POST_DEPLOY_SCRIPT"
                echo  "Your mungo_post_deploy has been found and has been executed"
         fi

  fi
}


if [ -x "$REPO_PRE_DEPLOY_SCRIPT" ]; then
       source "$REPO_PRE_DEPLOY_SCRIPT"
       echo   "Your mungo_pre_deploy has been found and has been executed"  
       start_app
else 
       start_app
fi
  


echo "-------> Deployment has completed"